# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='long',
            new_name='longitude',
        ),
    ]
