# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170407_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lon',
            new_name='longitude',
        ),
    ]
